name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@v3
      - uses: php-actions/phpunit@v3

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          php-version: '8.0'
          path: src/

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          php-version: '8.0'
          php_extensions: 'memcached apcu'
          memory_limit: 256M