name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6

      - name: PHPStan 2
        uses: php-actions/composer@v6
        with:
          command: analyse
          php_version: 8.0
          php_extensions: apcu memcached

      - name: PHPUnit tests
        uses: php-actions/composer@v6
        with:
          command: test-unit
          php_version: 8.0
          php_extensions: apcu memcached