name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@v3
      - uses: php-actions/phpunit@v3

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          php_version: 8.0
          path: src/

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.5
          php_version: 8.0
          php_extensions: memcached apcu
          configuration: phpunit.xml
          bootstrap: test/unit/bootstrap.php
          memory_limit: 256M